#POD IC-WEBAPP || Déploiement du service WEB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
      - name: ic-webapp
        image: votre_dockerhub/ic-webapp:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ODOO_URL
          value: "http://odoo.icgroup.local"
        - name: PGADMIN_URL
          value: "http://pgadmin.icgroup.local"